const typeAction = {
	// slide
	LIST_SLIDE: "LIST_SLIDE",
	REMOVE_SLIDE: "REMOVE_SLIDE",
	ADD_SLIDE: "ADD_SLIDE",
	DETAIL_SLIDE: "DETAIL_SLIDE",
	UPDATE_SLIDE: "UPDATE_SLIDE",

	// category
	LIST_CATEGORY: "LIST_CATEGORY",
	REMOVE_CATEGORY: "REMOVE_CATEGORY",
	ADD_CATEGORY: "ADD_CATEGORY",
	UPDATE_CATEGORY: "UPDATE_CATEGORY",

	// product
	LIST_PRODUCT: "LIST_PRODUCT",
	REMOVE_PRODUCT: "REMOVE_PRODUCT",
	ADD_PRODUCT: "ADD_PRODUCT",
	UPDATE_PRODUCT: "UPDATE_PRODUCT",
	DETAIL_PRODUCT: "DETAIL_PRODUCT",
	LOW_TO_HIGHT: "LOW_TO_HIGHT",
	HIGHT_TO_LOW: "HIGHT_TO_LOW",
	FILTER_CATE: "FILTER_CATE",

	// sub category
	LIST_SUBCATEGORY: "LIST_SUBCATEGORY",
	REMOVE_SUBCATEGORY: "REMOVE_SUBCATEGORY",
	ADD_SUBCATEGORY: "ADD_SUBCATEGORY",
	UPDATE_SUBCATEGORY: "UPDATE_SUBCATEGORY",
	SET_CHECKBOX: "SET_CHECKBOX",

	// login, logout
	SIGN_IN: "SIGN_IN",
	ERROR: "ERROR",
	SIGN_OUT: "SIGN_OUT",

	// user
	LIST_USER: "LIST_USER",
	ADD_USER: "ADD_USER",
	UPDATE_USER: "UPDATE_USER",
	REMOVE_USER: "REMOVE_USER",
	CLIENT_UPDATE: "CLIENT_UPDATE",
	ERROR_CLIENT_UPDATE: "ERROR_CLIENT_UPDATE",

	// comment
	ADD_COMMENT: "ADD_COMMENT",
	LIST_COMMENT: "LIST_COMMENT",
	REMOVE_COMMENT: "REMOVE_COMMENT",

	// cart
	ADD_TO_CART: "ADD_TO_CART",
	LIST_CART: "LIST_CART",
	UPDATE_CART: "UPDATE_CART",
	CLEAR_CART: "CLEAR_CART",
	INCREASE: "INCREASE",
	DECREASE: "DECREASE",
	REMOVE_CART: "REMOVE_CART",

	// order
	LIST_ORDER: "LIST_ORDER",
	REMOVE_ORDER: "REMOVE_ORDER",

	// order detail
	LIST_ORDER_DETAIL: "LIST_ORDER_DETAIL",
	UPDATE_STATUS: "UPDATE_STATUS",
};

export default typeAction;
