const typeAction = {
	// slide
	LIST_SLIDE: "LIST_SLIDE",
	REMOVE_SLIDE: "REMOVE_SLIDE",
	ADD_SLIDE: "ADD_SLIDE",
	DETAIL_SLIDE: "DETAIL_SLIDE",
	UPDATE_SLIDE: "UPDATE_SLIDE",

	// category
	LIST_CATEGORY: "LIST_CATEGORY",
	REMOVE_CATEGORY: "REMOVE_CATEGORY",
	ADD_CATEGORY: "ADD_CATEGORY",
	UPDATE_CATEGORY: "UPDATE_CATEGORY",

	// product
	LIST_PRODUCT: "LIST_PRODUCT",
	REMOVE_PRODUCT: "REMOVE_PRODUCT",
	ADD_PRODUCT: "ADD_PRODUCT",
	UPDATE_PRODUCT: "UPDATE_PRODUCT",
	DETAIL_PRODUCT: "DETAIL_PRODUCT",

	// sub category
	LIST_SUBCATEGORY: "LIST_SUBCATEGORY",
	REMOVE_SUBCATEGORY: "REMOVE_SUBCATEGORY",
	ADD_SUBCATEGORY: "ADD_SUBCATEGORY",
	UPDATE_SUBCATEGORY: "UPDATE_SUBCATEGORY",

	// login, logout
	SIGN_IN: "SIGN_IN",
	ERROR: "ERROR",
	SIGN_OUT: "SIGN_OUT",

	// comment
	ADD_COMMENT: "ADD_COMMENT",
	LIST_COMMENT: "LIST_COMMENT",
};

export default typeAction;
